import { Injectable } from '@angular/core';


@Injectable({
    providedIn: 'root'
})
export class CommonDetailsService {
    constructor() {

    }
    public days: any[] = ['1', '2','3','4','5','6','7','8','9','10','11','12',
    '13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'
    ];
    public months: any[] = ['Jan', 'Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    public nationality: any[] = ['Indian', 'Others'];
    public bloodGroup: any[] = ["O-",
        "O+",
        "A-",
        "A+",
        "B-",
        "B+",
        "AB-",
        "AB+"];
    public community :any[]=['OC','SC','ST','BC','MBC'];
     public source :any[]=['NewsPaper','Social media','walkin','Through Friend'];
     public board :any[]=['STATE BOARD','CBSE','ICSE','OTHERS'];
     public markingScheme:any[]= ['PERCENTAGE','CGPA'];
     public states:any[]= ["Andhra Pradesh","Andaman and Nicobar Islands","Arunachal Pradesh","Assam",
    "Bihar","Chandigarh","Dadar and Nagar Haveli","Daman and Diu","Delhi","Lakshadweep","Puducherry",
"Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Madhya Pradesh",
"Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu",
"Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"]

    public countries :any=
        { "country" : [
            {"country": "Afghanistan", "countryCode": "AF"},
            {"country": "Åland Islands", "countryCode": "AX"},
            {"country": "Albania", "countryCode": "AL"},
            {"country": "Algeria", "countryCode": "DZ"},
            {"country": "American Samoa", "countryCode": "AS"},
            {"country": "AndorrA", "countryCode": "AD"},
            {"country": "Angola", "countryCode": "AO"},
            {"country": "Anguilla", "countryCode": "AI"},
            {"country": "Antarctica", "countryCode": "AQ"},
            {"country": "Antigua and Barbuda", "countryCode": "AG"},
            {"country": "Argentina", "countryCode": "AR"},
            {"country": "Armenia", "countryCode": "AM"},
            {"country": "Aruba", "countryCode": "AW"},
            {"country": "Australia", "countryCode": "AU"},
            {"country": "Austria", "countryCode": "AT"},
            {"country": "Azerbaijan", "countryCode": "AZ"},
            {"country": "Bahamas", "countryCode": "BS"},
            {"country": "Bahrain", "countryCode": "BH"},
            {"country": "Bangladesh", "countryCode": "BD"},
            {"country": "Barbados", "countryCode": "BB"},
            {"country": "Belarus", "countryCode": "BY"},
            {"country": "Belgium", "countryCode": "BE"},
            {"country": "Belize", "countryCode": "BZ"},
            {"country": "Benin", "countryCode": "BJ"},
            {"country": "Bermuda", "countryCode": "BM"},
            {"country": "Bhutan", "countryCode": "BT"},
            {"country": "Bolivia", "countryCode": "BO"},
            {"country": "Bosnia and Herzegovina", "countryCode": "BA"},
            {"country": "Botswana", "countryCode": "BW"},
            {"country": "Bouvet Island", "countryCode": "BV"},
            {"country": "Brazil", "countryCode": "BR"},
            {"country": "British Indian Ocean Territory", "countryCode": "IO"},
            {"country": "Brunei Darussalam", "countryCode": "BN"},
            {"country": "Bulgaria", "countryCode": "BG"},
            {"country": "Burkina Faso", "countryCode": "BF"},
            {"country": "Burundi", "countryCode": "BI"},
            {"country": "Cambodia", "countryCode": "KH"},
            {"country": "Cameroon", "countryCode": "CM"},
            {"country": "Canada", "countryCode": "CA"},
            {"country": "Cape Verde", "countryCode": "CV"},
            {"country": "Cayman Islands", "countryCode": "KY"},
            {"country": "Central African Republic", "countryCode": "CF"},
            {"country": "Chad", "countryCode": "TD"},
            {"country": "Chile", "countryCode": "CL"},
            {"country": "China", "countryCode": "CN"},
            {"country": "Christmas Island", "countryCode": "CX"},
            {"country": "Cocos (Keeling) Islands", "countryCode": "CC"},
            {"country": "Colombia", "countryCode": "CO"},
            {"country": "Comoros", "countryCode": "KM"},
            {"country": "Congo", "countryCode": "CG"},
            {"country": "Congo", "countryCode": "CD"},
            {"country": "Cook Islands", "countryCode": "CK"},
            {"country": "Costa Rica", "countryCode": "CR"},
            {"country": "Cote D\"Ivoire", "countryCode": "CI"},
            {"country": "Croatia", "countryCode": "HR"},
            {"country": "Cuba", "countryCode": "CU"},
            {"country": "Cyprus", "countryCode": "CY"},
            {"country": "Czech Republic", "countryCode": "CZ"},
            {"country": "Denmark", "countryCode": "DK"},
            {"country": "Djibouti", "countryCode": "DJ"},
            {"country": "Dominica", "countryCode": "DM"},
            {"country": "Dominican Republic", "countryCode": "DO"},
            {"country": "Ecuador", "countryCode": "EC"},
            {"country": "Egypt", "countryCode": "EG"},
            {"country": "El Salvador", "countryCode": "SV"},
            {"country": "Equatorial Guinea", "countryCode": "GQ"},
            {"country": "Eritrea", "countryCode": "ER"},
            {"country": "Estonia", "countryCode": "EE"},
            {"country": "Ethiopia", "countryCode": "ET"},
            {"country": "Falkland Islands (Malvinas)", "countryCode": "FK"},
            {"country": "Faroe Islands", "countryCode": "FO"},
            {"country": "Fiji", "countryCode": "FJ"},
            {"country": "Finland", "countryCode": "FI"},
            {"country": "France", "countryCode": "FR"},
            {"country": "French Guiana", "countryCode": "GF"},
            {"country": "French Polynesia", "countryCode": "PF"},
            {"country": "French Southern Territories", "countryCode": "TF"},
            {"country": "Gabon", "countryCode": "GA"},
            {"country": "Gambia", "countryCode": "GM"},
            {"country": "Georgia", "countryCode": "GE"},
            {"country": "Germany", "countryCode": "DE"},
            {"country": "Ghana", "countryCode": "GH"},
            {"country": "Gibraltar", "countryCode": "GI"},
            {"country": "Greece", "countryCode": "GR"},
            {"country": "Greenland", "countryCode": "GL"},
            {"country": "Grenada", "countryCode": "GD"},
            {"country": "Guadeloupe", "countryCode": "GP"},
            {"country": "Guam", "countryCode": "GU"},
            {"country": "Guatemala", "countryCode": "GT"},
            {"country": "Guernsey", "countryCode": "GG"},
            {"country": "Guinea", "countryCode": "GN"},
            {"country": "Guinea-Bissau", "countryCode": "GW"},
            {"country": "Guyana", "countryCode": "GY"},
            {"country": "Haiti", "countryCode": "HT"},
            {"country": "Heard Island and Mcdonald Islands", "countryCode": "HM"},
            {"country": "Holy See (Vatican City State)", "countryCode": "VA"},
            {"country": "Honduras", "countryCode": "HN"},
            {"country": "Hong Kong", "countryCode": "HK"},
            {"country": "Hungary", "countryCode": "HU"},
            {"country": "Iceland", "countryCode": "IS"},
            {"country": "India", "countryCode": "IN"},
            {"country": "Indonesia", "countryCode": "ID"},
            {"country": "Iran", "countryCode": "IR"},
            {"country": "Iraq", "countryCode": "IQ"},
            {"country": "Ireland", "countryCode": "IE"},
            {"country": "Isle of Man", "countryCode": "IM"},
            {"country": "Israel", "countryCode": "IL"},
            {"country": "Italy", "countryCode": "IT"},
            {"country": "Jamaica", "countryCode": "JM"},
            {"country": "Japan", "countryCode": "JP"},
            {"country": "Jersey", "countryCode": "JE"},
            {"country": "Jordan", "countryCode": "JO"},
            {"country": "Kazakhstan", "countryCode": "KZ"},
            {"country": "Kenya", "countryCode": "KE"},
            {"country": "Kiribati", "countryCode": "KI"},
            {"country": "Korea Democratic People\'S Republic", "countryCode": "KP"},
            {"country": "Korea", "countryCode": "KR"},
            {"country": "Kuwait", "countryCode": "KW"},
            {"country": "Kyrgyzstan", "countryCode": "KG"},
            {"country": "Lao People\"S Democratic Republic", "countryCode": "LA"},
            {"country": "Latvia", "countryCode": "LV"},
            {"country": "Lebanon", "countryCode": "LB"},
            {"country": "Lesotho", "countryCode": "LS"},
            {"country": "Liberia", "countryCode": "LR"},
            {"country": "Libyan Arab Jamahiriya", "countryCode": "LY"},
            {"country": "Liechtenstein", "countryCode": "LI"},
            {"country": "Lithuania", "countryCode": "LT"},
            {"country": "Luxembourg", "countryCode": "LU"},
            {"country": "Macao", "countryCode": "MO"},
            {"country": "Macedonia  The Former Yugoslav Republic", "countryCode": "MK"},
            {"country": "Madagascar", "countryCode": "MG"},
            {"country": "Malawi", "countryCode": "MW"},
            {"country": "Malaysia", "countryCode": "MY"},
            {"country": "Maldives", "countryCode": "MV"},
            {"country": "Mali", "countryCode": "ML"},
            {"country": "Malta", "countryCode": "MT"},
            {"country": "Marshall Islands", "countryCode": "MH"},
            {"country": "Martinique", "countryCode": "MQ"},
            {"country": "Mauritania", "countryCode": "MR"},
            {"country": "Mauritius", "countryCode": "MU"},
            {"country": "Mayotte", "countryCode": "YT"},
            {"country": "Mexico", "countryCode": "MX"},
            {"country": "Micronesia", "countryCode": "FM"},
            {"country": "Moldova", "countryCode": "MD"},
            {"country": "Monaco", "countryCode": "MC"},
            {"country": "Mongolia", "countryCode": "MN"},
            {"country": "Montserrat", "countryCode": "MS"},
            {"country": "Morocco", "countryCode": "MA"},
            {"country": "Mozambique", "countryCode": "MZ"},
            {"country": "Myanmar", "countryCode": "MM"},
            {"country": "Namibia", "countryCode": "NA"},
            {"country": "Nauru", "countryCode": "NR"},
            {"country": "Nepal", "countryCode": "NP"},
            {"country": "Netherlands", "countryCode": "NL"},
            {"country": "Netherlands Antilles", "countryCode": "AN"},
            {"country": "New Caledonia", "countryCode": "NC"},
            {"country": "New Zealand", "countryCode": "NZ"},
            {"country": "Nicaragua", "countryCode": "NI"},
            {"country": "Niger", "countryCode": "NE"},
            {"country": "Nigeria", "countryCode": "NG"},
            {"country": "Niue", "countryCode": "NU"},
            {"country": "Norfolk Island", "countryCode": "NF"},
            {"country": "Northern Mariana Islands", "countryCode": "MP"},
            {"country": "Norway", "countryCode": "NO"},
            {"country": "Oman", "countryCode": "OM"},
            {"country": "Pakistan", "countryCode": "PK"},
            {"country": "Palau", "countryCode": "PW"},
            {"country": "Palestinian Territory Occupied", "countryCode": "PS"},
            {"country": "Panama", "countryCode": "PA"},
            {"country": "Papua New Guinea", "countryCode": "PG"},
            {"country": "Paraguay", "countryCode": "PY"},
            {"country": "Peru", "countryCode": "PE"},
            {"country": "Philippines", "countryCode": "PH"},
            {"country": "Pitcairn", "countryCode": "PN"},
            {"country": "Poland", "countryCode": "PL"},
            {"country": "Portugal", "countryCode": "PT"},
            {"country": "Puerto Rico", "countryCode": "PR"},
            {"country": "Qatar", "countryCode": "QA"},
            {"country": "Reunion", "countryCode": "RE"},
            {"country": "Romania", "countryCode": "RO"},
            {"country": "Russian Federation", "countryCode": "RU"},
            {"country": "RWANDA", "countryCode": "RW"},
            {"country": "Saint Helena", "countryCode": "SH"},
            {"country": "Saint Kitts and Nevis", "countryCode": "KN"},
            {"country": "Saint Lucia", "countryCode": "LC"},
            {"country": "Saint Pierre and Miquelon", "countryCode": "PM"},
            {"country": "Saint Vincent and the Grenadines", "countryCode": "VC"},
            {"country": "Samoa", "countryCode": "WS"},
            {"country": "San Marino", "countryCode": "SM"},
            {"country": "Sao Tome and Principe", "countryCode": "ST"},
            {"country": "Saudi Arabia", "countryCode": "SA"},
            {"country": "Senegal", "countryCode": "SN"},
            {"country": "Serbia and Montenegro", "countryCode": "CS"},
            {"country": "Seychelles", "countryCode": "SC"},
            {"country": "Sierra Leone", "countryCode": "SL"},
            {"country": "Singapore", "countryCode": "SG"},
            {"country": "Slovakia", "countryCode": "SK"},
            {"country": "Slovenia", "countryCode": "SI"},
            {"country": "Solomon Islands", "countryCode": "SB"},
            {"country": "Somalia", "countryCode": "SO"},
            {"country": "South Africa", "countryCode": "ZA"},
            {"country": "South Georgia and the South Sandwich Islands", "countryCode": "GS"},
            {"country": "Spain", "countryCode": "ES"},
            {"country": "Sri Lanka", "countryCode": "LK"},
            {"country": "Sudan", "countryCode": "SD"},
            {"country": "Suricountry", "countryCode": "SR"},
            {"country": "Svalbard and Jan Mayen", "countryCode": "SJ"},
            {"country": "Swaziland", "countryCode": "SZ"},
            {"country": "Sweden", "countryCode": "SE"},
            {"country": "Switzerland", "countryCode": "CH"},
            {"country": "Syrian Arab Republic", "countryCode": "SY"},
            {"country": "Taiwan Province of China", "countryCode": "TW"},
            {"country": "Tajikistan", "countryCode": "TJ"},
            {"country": "Tanzania", "countryCode": "TZ"},
            {"country": "Thailand", "countryCode": "TH"},
            {"country": "Timor-Leste", "countryCode": "TL"},
            {"country": "Togo", "countryCode": "TG"},
            {"country": "Tokelau", "countryCode": "TK"},
            {"country": "Tonga", "countryCode": "TO"},
            {"country": "Trinidad and Tobago", "countryCode": "TT"},
            {"country": "Tunisia", "countryCode": "TN"},
            {"country": "Turkey", "countryCode": "TR"},
            {"country": "Turkmenistan", "countryCode": "TM"},
            {"country": "Turks and Caicos Islands", "countryCode": "TC"},
            {"country": "Tuvalu", "countryCode": "TV"},
            {"country": "Uganda", "countryCode": "UG"},
            {"country": "Ukraine", "countryCode": "UA"},
            {"country": "United Arab Emirates", "countryCode": "AE"},
            {"country": "United Kingdom", "countryCode": "GB"},
            {"country": "United States", "countryCode": "US"},
            {"country": "United States Minor Outlying Islands", "countryCode": "UM"},
            {"country": "Uruguay", "countryCode": "UY"},
            {"country": "Uzbekistan", "countryCode": "UZ"},
            {"country": "Vanuatu", "countryCode": "VU"},
            {"country": "Venezuela", "countryCode": "VE"},
            {"country": "Viet Nam", "countryCode": "VN"},
            {"country": " British Virgin Islands", "countryCode": "VG"},
            {"country": "Virgin Islands", "countryCode": "VI"},
            {"country": "Wallis and Futuna", "countryCode": "WF"},
            {"country": "Western Sahara", "countryCode": "EH"},
            {"country": "Yemen", "countryCode": "YE"},
            {"country": "Zambia", "countryCode": "ZM"},
            {"country": "Zimbabwe", "countryCode": "ZW" },
                    ]}
    
    
}